# Startup config.yml file

default:
  studyName: ohdsi_study
  cohortTableName: cohorts

# a dummy block is added as a guide
example:
  databaseName: example
  connectionDetails: !expr DatabaseConnector::createConnectionDetails(
    dbms = keyring::key_get("example_dbms"),
    user = keyring::key_get("example_user"),
    password = keyring::key_get("example_password"),
    server = keyring::key_get("example_server"),
    port = keyring::key_get('example_port'))
  cdm: !expr keyring::key_get("example_cdm")
  vocab: !expr keyring::key_get("example_vocab")
  write: !expr keyring::key_get("example_write")
