# Config File for {{{ Project }}}

default:
  projectName: {{{ Project }}}

# Config block for {{{ Block }}}

{{{ Block }}}:
  databaseName: {{{ Database }}}
  connectionDetails: !expr DatabaseConnector::createConnectionDetails(
    dbms = keyring::key_get('{{{ Block }}}_dbms'),
    user = keyring::key_get('{{{ Block }}}_user'),
    password = keyring::key_get('{{{ Block }}}_password'),
    connectionString = keyring::key_get('{{{ Block }}}_connectionString'))
  cdmDatabase: !expr keyring::key_get('{{{ Block }}}_cdmDatabase')
  cdmSchema: !expr keyring::key_get('{{{ Block }}}_cdmSchema')
  vocabSchema: !expr keyring::key_get('{{{ Block }}}_vocabSchema')
  writeDatabase: !expr keyring::key_get('{{{ Block }}}_writeDatabase')
  writeSchema: !expr keyring::key_get('{{{ Block }}}_writeSchema')
  role: !expr keyring::key_get('{{{ Block }}}_role')
  cohortTable: {{{ Cohort }}}
